stages:
  process_raw_diabetes_data:
    cmd: poetry run python diabetes_classifier/data/process_data.py
    deps:
      - diabetes_classifier/data/process_data.py
      - data/raw/diabetes.csv
    outs: 
      - data/processed/diabetes.csv
  create_train_test_data:
    cmd: poetry run python diabetes_classifier/data/create_train_test_data.py
    params:
      - xgboost_training.training_percentage
    deps:
      - diabetes_classifier/data/create_train_test_data.py
      - data/processed/diabetes.csv
    outs:
      - data/processed/train.pkl
      - data/processed/test.pkl
